Repository trossr32/sonarr-radarr-lidarr-autosearch-browser-extension, pull requests merged in 2022-01, with the labels that each got.

#82 71 cater for radarr v4
  README.md
  Test Docker Notes/docker.ps1
  src/content/js/core.js
  src/manifest.json
Labels: enhancement

#83 Staging
  README.md
  Test Docker Notes/docker.ps1
  src/content/js/core.js
  src/manifest.json
Labels: release

#85 feat: add senscritique.com integration
  src/content/assets/images/integrations/senscritique.png
  src/content/js/content_script.js
  src/content/js/core.js
Labels: enhancement

#84 feat: add allocine.fr integration
  src/content/assets/images/integrations/allocine.png
  src/content/js/content_script.js
  src/content/js/core.js
Labels: enhancement

#87 86 fix context menu not updating on settings change
  src/eventPage.js
Labels: bug

#88 Staging
  README.md
  src/content/assets/images/integrations/allocine.png
  src/content/assets/images/integrations/senscritique.png
  src/content/js/content_script.js
  src/content/js/core.js
  src/eventPage.js
  src/manifest.json
Labels: bug, enhancement
